// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvsnpqombibrcdqnabyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2c25wcW9tYmlicmNkcW5hYnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzMxMDAsImV4cCI6MjA2Mjk0OTEwMH0.8NsD914FtAE1sK35Sl8DpXjxhMe4oYstCI3JOJh8axc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);